// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: ui_spin_coater

#include "ui.h"

lv_obj_t * ui_Analog = NULL;
lv_obj_t * ui_bgrAnalog = NULL;
lv_obj_t * ui_buttonHomeAnalog = NULL;
lv_obj_t * ui_buttonStopAnalog = NULL;
lv_obj_t * ui_labelStopAnalog = NULL;
lv_obj_t * ui_buttonStarAnalog = NULL;
lv_obj_t * ui_labelStartAnalog = NULL;
lv_obj_t * ui_buttonPausAnalog = NULL;
lv_obj_t * ui_labelPauseAnalog = NULL;
lv_obj_t * ui_labelDataSrpmAnalog = NULL;
lv_obj_t * ui_labelDataMrpmAnalog = NULL;
lv_obj_t * ui_labelDataTimeAnalog = NULL;
// event funtions
void ui_event_buttonHomeAnalog(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Home_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        Button_SetSateIDLE_Analog(e);
    }
}

void ui_event_buttonStopAnalog(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Button_StopAnalog(e);
    }
}

void ui_event_buttonStarAnalog(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Button_StartAnalog(e);
    }
}

void ui_event_buttonPausAnalog(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Button_SetRpm(e);
    }
}

// build funtions

void ui_Analog_screen_init(void)
{
    ui_Analog = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Analog, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bgrAnalog = lv_image_create(ui_Analog);
    lv_image_set_src(ui_bgrAnalog, &ui_img_analogscreen_png);
    lv_obj_set_width(ui_bgrAnalog, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bgrAnalog, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bgrAnalog, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bgrAnalog, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_bgrAnalog, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_buttonHomeAnalog = lv_imagebutton_create(ui_Analog);
    lv_imagebutton_set_src(ui_buttonHomeAnalog, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_670667251, NULL);
    lv_imagebutton_set_src(ui_buttonHomeAnalog, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_670667251, NULL);
    lv_obj_set_width(ui_buttonHomeAnalog, 40);
    lv_obj_set_height(ui_buttonHomeAnalog, 40);
    lv_obj_set_x(ui_buttonHomeAnalog, -213);
    lv_obj_set_y(ui_buttonHomeAnalog, -136);
    lv_obj_set_align(ui_buttonHomeAnalog, LV_ALIGN_CENTER);

    ui_buttonStopAnalog = lv_button_create(ui_Analog);
    lv_obj_set_width(ui_buttonStopAnalog, 160);
    lv_obj_set_height(ui_buttonStopAnalog, 50);
    lv_obj_set_x(ui_buttonStopAnalog, -160);
    lv_obj_set_y(ui_buttonStopAnalog, 135);
    lv_obj_set_align(ui_buttonStopAnalog, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonStopAnalog, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonStopAnalog, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonStopAnalog, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonStopAnalog, lv_color_hex(0xE64A4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonStopAnalog, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelStopAnalog = lv_label_create(ui_buttonStopAnalog);
    lv_obj_set_width(ui_labelStopAnalog, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelStopAnalog, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelStopAnalog, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelStopAnalog, "STOP");
    lv_obj_set_style_text_color(ui_labelStopAnalog, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelStopAnalog, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelStopAnalog, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonStarAnalog = lv_button_create(ui_Analog);
    lv_obj_set_width(ui_buttonStarAnalog, 160);
    lv_obj_set_height(ui_buttonStarAnalog, 50);
    lv_obj_set_x(ui_buttonStarAnalog, 160);
    lv_obj_set_y(ui_buttonStarAnalog, 135);
    lv_obj_set_align(ui_buttonStarAnalog, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonStarAnalog, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonStarAnalog, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonStarAnalog, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonStarAnalog, lv_color_hex(0x10B981), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonStarAnalog, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelStartAnalog = lv_label_create(ui_buttonStarAnalog);
    lv_obj_set_width(ui_labelStartAnalog, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelStartAnalog, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelStartAnalog, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelStartAnalog, "START");
    lv_obj_set_style_text_color(ui_labelStartAnalog, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelStartAnalog, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelStartAnalog, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonPausAnalog = lv_button_create(ui_Analog);
    lv_obj_set_width(ui_buttonPausAnalog, 160);
    lv_obj_set_height(ui_buttonPausAnalog, 50);
    lv_obj_set_x(ui_buttonPausAnalog, 0);
    lv_obj_set_y(ui_buttonPausAnalog, 135);
    lv_obj_set_align(ui_buttonPausAnalog, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonPausAnalog, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonPausAnalog, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonPausAnalog, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonPausAnalog, lv_color_hex(0x9CA3AF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonPausAnalog, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelPauseAnalog = lv_label_create(ui_buttonPausAnalog);
    lv_obj_set_width(ui_labelPauseAnalog, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelPauseAnalog, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelPauseAnalog, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelPauseAnalog, "PAUSE");
    lv_obj_set_style_text_color(ui_labelPauseAnalog, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelPauseAnalog, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelPauseAnalog, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelDataSrpmAnalog = lv_label_create(ui_Analog);
    lv_obj_set_width(ui_labelDataSrpmAnalog, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelDataSrpmAnalog, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelDataSrpmAnalog, 141);
    lv_obj_set_y(ui_labelDataSrpmAnalog, 75);
    lv_obj_set_align(ui_labelDataSrpmAnalog, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelDataSrpmAnalog, "0");
    lv_obj_set_style_text_color(ui_labelDataSrpmAnalog, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelDataSrpmAnalog, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelDataSrpmAnalog, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelDataMrpmAnalog = lv_label_create(ui_Analog);
    lv_obj_set_width(ui_labelDataMrpmAnalog, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelDataMrpmAnalog, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelDataMrpmAnalog, 141);
    lv_obj_set_y(ui_labelDataMrpmAnalog, -2);
    lv_obj_set_align(ui_labelDataMrpmAnalog, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelDataMrpmAnalog, "0");
    lv_obj_set_style_text_color(ui_labelDataMrpmAnalog, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelDataMrpmAnalog, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelDataMrpmAnalog, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelDataTimeAnalog = lv_label_create(ui_Analog);
    lv_obj_set_width(ui_labelDataTimeAnalog, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelDataTimeAnalog, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelDataTimeAnalog, 141);
    lv_obj_set_y(ui_labelDataTimeAnalog, -77);
    lv_obj_set_align(ui_labelDataTimeAnalog, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelDataTimeAnalog, "0");
    lv_obj_set_style_text_color(ui_labelDataTimeAnalog, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelDataTimeAnalog, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelDataTimeAnalog, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_buttonHomeAnalog, ui_event_buttonHomeAnalog, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonStopAnalog, ui_event_buttonStopAnalog, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonStarAnalog, ui_event_buttonStarAnalog, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonPausAnalog, ui_event_buttonPausAnalog, LV_EVENT_ALL, NULL);

}

void ui_Analog_screen_destroy(void)
{
    if(ui_Analog) lv_obj_del(ui_Analog);

    // NULL screen variables
    ui_Analog = NULL;
    ui_bgrAnalog = NULL;
    ui_buttonHomeAnalog = NULL;
    ui_buttonStopAnalog = NULL;
    ui_labelStopAnalog = NULL;
    ui_buttonStarAnalog = NULL;
    ui_labelStartAnalog = NULL;
    ui_buttonPausAnalog = NULL;
    ui_labelPauseAnalog = NULL;
    ui_labelDataSrpmAnalog = NULL;
    ui_labelDataMrpmAnalog = NULL;
    ui_labelDataTimeAnalog = NULL;

}
