// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: ui_spin_coater

#ifndef UI_ANALOG_H
#define UI_ANALOG_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Analog
extern void ui_Analog_screen_init(void);
extern void ui_Analog_screen_destroy(void);
extern lv_obj_t * ui_Analog;
extern lv_obj_t * ui_bgrAnalog;
extern void ui_event_buttonHomeAnalog(lv_event_t * e);
extern lv_obj_t * ui_buttonHomeAnalog;
extern void ui_event_buttonStopAnalog(lv_event_t * e);
extern lv_obj_t * ui_buttonStopAnalog;
extern lv_obj_t * ui_labelStopAnalog;
extern void ui_event_buttonStarAnalog(lv_event_t * e);
extern lv_obj_t * ui_buttonStarAnalog;
extern lv_obj_t * ui_labelStartAnalog;
extern void ui_event_buttonPausAnalog(lv_event_t * e);
extern lv_obj_t * ui_buttonPausAnalog;
extern lv_obj_t * ui_labelPauseAnalog;
extern lv_obj_t * ui_labelDataSrpmAnalog;
extern lv_obj_t * ui_labelDataMrpmAnalog;
extern lv_obj_t * ui_labelDataTimeAnalog;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

