// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: ui_spin_coater

#include "ui.h"

lv_obj_t * ui_Digital = NULL;
lv_obj_t * ui_bgrDigital = NULL;
lv_obj_t * ui_buttonStopDigital = NULL;
lv_obj_t * ui_labelStopDigital = NULL;
lv_obj_t * ui_buttonStarDigital = NULL;
lv_obj_t * ui_labelStartDigital = NULL;
lv_obj_t * ui_buttonUpIncDigital = NULL;
lv_obj_t * ui_labelUpIncDigital = NULL;
lv_obj_t * ui_buttonDownIncDigital = NULL;
lv_obj_t * ui_labelDownIncDigital = NULL;
lv_obj_t * ui_buttonUpSrpmDigital = NULL;
lv_obj_t * ui_labelUpSrpmDigital = NULL;
lv_obj_t * ui_buttonDownSrpmDigital = NULL;
lv_obj_t * ui_labelDownSrpmDigital = NULL;
lv_obj_t * ui_panelPauseDigital = NULL;
lv_obj_t * ui_labelPauseDigital = NULL;
lv_obj_t * ui_buttonHomeDigital = NULL;
lv_obj_t * ui_labelDataTimeDigital = NULL;
lv_obj_t * ui_labelDataMrpmDigital = NULL;
lv_obj_t * ui_labelDataSrpmDigital = NULL;
lv_obj_t * ui_labelDataIncDigital = NULL;
// event funtions
void ui_event_buttonStopDigital(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Button_StopDigital(e);
    }
}

void ui_event_buttonStarDigital(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Button_StartDigital(e);
    }
}

void ui_event_buttonUpIncDigital(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Button_UpInc(e);
    }
}

void ui_event_buttonDownIncDigital(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Button_DownInc(e);
    }
}

void ui_event_buttonUpSrpmDigital(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ButtonUpSrpm(e);
    }
}

void ui_event_buttonDownSrpmDigital(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Button_DownSrpm(e);
    }
}

void ui_event_buttonHomeDigital(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Home_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        Button_SetStateIDLE_Digital(e);
    }
}

// build funtions

void ui_Digital_screen_init(void)
{
    ui_Digital = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Digital, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bgrDigital = lv_image_create(ui_Digital);
    lv_image_set_src(ui_bgrDigital, &ui_img_digitalscreen_png);
    lv_obj_set_width(ui_bgrDigital, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bgrDigital, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bgrDigital, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bgrDigital, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_bgrDigital, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_buttonStopDigital = lv_button_create(ui_Digital);
    lv_obj_set_width(ui_buttonStopDigital, 160);
    lv_obj_set_height(ui_buttonStopDigital, 50);
    lv_obj_set_x(ui_buttonStopDigital, -160);
    lv_obj_set_y(ui_buttonStopDigital, 135);
    lv_obj_set_align(ui_buttonStopDigital, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonStopDigital, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonStopDigital, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonStopDigital, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonStopDigital, lv_color_hex(0xE64A4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonStopDigital, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelStopDigital = lv_label_create(ui_buttonStopDigital);
    lv_obj_set_width(ui_labelStopDigital, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelStopDigital, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelStopDigital, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelStopDigital, "STOP");
    lv_obj_set_style_text_color(ui_labelStopDigital, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelStopDigital, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelStopDigital, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonStarDigital = lv_button_create(ui_Digital);
    lv_obj_set_width(ui_buttonStarDigital, 160);
    lv_obj_set_height(ui_buttonStarDigital, 50);
    lv_obj_set_x(ui_buttonStarDigital, 160);
    lv_obj_set_y(ui_buttonStarDigital, 135);
    lv_obj_set_align(ui_buttonStarDigital, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonStarDigital, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonStarDigital, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonStarDigital, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonStarDigital, lv_color_hex(0x10B981), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonStarDigital, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelStartDigital = lv_label_create(ui_buttonStarDigital);
    lv_obj_set_width(ui_labelStartDigital, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelStartDigital, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelStartDigital, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelStartDigital, "START");
    lv_obj_set_style_text_color(ui_labelStartDigital, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelStartDigital, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelStartDigital, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonUpIncDigital = lv_button_create(ui_Digital);
    lv_obj_set_width(ui_buttonUpIncDigital, 45);
    lv_obj_set_height(ui_buttonUpIncDigital, 45);
    lv_obj_set_x(ui_buttonUpIncDigital, 209);
    lv_obj_set_y(ui_buttonUpIncDigital, 81);
    lv_obj_set_align(ui_buttonUpIncDigital, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonUpIncDigital, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonUpIncDigital, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonUpIncDigital, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonUpIncDigital, lv_color_hex(0xD1D5DB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonUpIncDigital, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_buttonUpIncDigital, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_buttonUpIncDigital, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelUpIncDigital = lv_label_create(ui_buttonUpIncDigital);
    lv_obj_set_width(ui_labelUpIncDigital, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelUpIncDigital, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelUpIncDigital, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelUpIncDigital, "+");
    lv_obj_set_style_text_color(ui_labelUpIncDigital, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelUpIncDigital, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelUpIncDigital, &ui_font_MonterLight36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonDownIncDigital = lv_button_create(ui_Digital);
    lv_obj_set_width(ui_buttonDownIncDigital, 45);
    lv_obj_set_height(ui_buttonDownIncDigital, 45);
    lv_obj_set_x(ui_buttonDownIncDigital, 161);
    lv_obj_set_y(ui_buttonDownIncDigital, 81);
    lv_obj_set_align(ui_buttonDownIncDigital, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonDownIncDigital, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonDownIncDigital, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonDownIncDigital, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonDownIncDigital, lv_color_hex(0xD1D5DB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonDownIncDigital, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_buttonDownIncDigital, lv_color_hex(0x231F20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_buttonDownIncDigital, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_buttonDownIncDigital, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_buttonDownIncDigital, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelDownIncDigital = lv_label_create(ui_buttonDownIncDigital);
    lv_obj_set_width(ui_labelDownIncDigital, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelDownIncDigital, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelDownIncDigital, 0);
    lv_obj_set_y(ui_labelDownIncDigital, -3);
    lv_obj_set_align(ui_labelDownIncDigital, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelDownIncDigital, "-");
    lv_obj_set_style_text_color(ui_labelDownIncDigital, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelDownIncDigital, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelDownIncDigital, &ui_font_MonterLight48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonUpSrpmDigital = lv_button_create(ui_Digital);
    lv_obj_set_width(ui_buttonUpSrpmDigital, 45);
    lv_obj_set_height(ui_buttonUpSrpmDigital, 45);
    lv_obj_set_x(ui_buttonUpSrpmDigital, 209);
    lv_obj_set_y(ui_buttonUpSrpmDigital, 26);
    lv_obj_set_align(ui_buttonUpSrpmDigital, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonUpSrpmDigital, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonUpSrpmDigital, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonUpSrpmDigital, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonUpSrpmDigital, lv_color_hex(0xD1D5DB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonUpSrpmDigital, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_buttonUpSrpmDigital, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_buttonUpSrpmDigital, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelUpSrpmDigital = lv_label_create(ui_buttonUpSrpmDigital);
    lv_obj_set_width(ui_labelUpSrpmDigital, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelUpSrpmDigital, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelUpSrpmDigital, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelUpSrpmDigital, "+");
    lv_obj_set_style_text_color(ui_labelUpSrpmDigital, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelUpSrpmDigital, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelUpSrpmDigital, &ui_font_MonterLight36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonDownSrpmDigital = lv_button_create(ui_Digital);
    lv_obj_set_width(ui_buttonDownSrpmDigital, 45);
    lv_obj_set_height(ui_buttonDownSrpmDigital, 45);
    lv_obj_set_x(ui_buttonDownSrpmDigital, 161);
    lv_obj_set_y(ui_buttonDownSrpmDigital, 26);
    lv_obj_set_align(ui_buttonDownSrpmDigital, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonDownSrpmDigital, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonDownSrpmDigital, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonDownSrpmDigital, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonDownSrpmDigital, lv_color_hex(0xD1D5DB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonDownSrpmDigital, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_buttonDownSrpmDigital, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_buttonDownSrpmDigital, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelDownSrpmDigital = lv_label_create(ui_buttonDownSrpmDigital);
    lv_obj_set_width(ui_labelDownSrpmDigital, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelDownSrpmDigital, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelDownSrpmDigital, 0);
    lv_obj_set_y(ui_labelDownSrpmDigital, -3);
    lv_obj_set_align(ui_labelDownSrpmDigital, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelDownSrpmDigital, "-");
    lv_obj_set_style_text_color(ui_labelDownSrpmDigital, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelDownSrpmDigital, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelDownSrpmDigital, &ui_font_MonterLight48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panelPauseDigital = lv_obj_create(ui_Digital);
    lv_obj_set_width(ui_panelPauseDigital, 160);
    lv_obj_set_height(ui_panelPauseDigital, 50);
    lv_obj_set_x(ui_panelPauseDigital, 0);
    lv_obj_set_y(ui_panelPauseDigital, 135);
    lv_obj_set_align(ui_panelPauseDigital, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panelPauseDigital, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panelPauseDigital, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panelPauseDigital, lv_color_hex(0x9CA3AF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelPauseDigital, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panelPauseDigital, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panelPauseDigital, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_panelPauseDigital, lv_color_hex(0x9CA3AF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_panelPauseDigital, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_panelPauseDigital, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_panelPauseDigital, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelPauseDigital = lv_label_create(ui_panelPauseDigital);
    lv_obj_set_width(ui_labelPauseDigital, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelPauseDigital, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelPauseDigital, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelPauseDigital, "PAUSE");
    lv_obj_set_style_text_color(ui_labelPauseDigital, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelPauseDigital, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelPauseDigital, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonHomeDigital = lv_imagebutton_create(ui_Digital);
    lv_imagebutton_set_src(ui_buttonHomeDigital, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_670667251, NULL);
    lv_imagebutton_set_src(ui_buttonHomeDigital, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_670667251, NULL);
    lv_obj_set_width(ui_buttonHomeDigital, 40);
    lv_obj_set_height(ui_buttonHomeDigital, 40);
    lv_obj_set_x(ui_buttonHomeDigital, -213);
    lv_obj_set_y(ui_buttonHomeDigital, -136);
    lv_obj_set_align(ui_buttonHomeDigital, LV_ALIGN_CENTER);

    ui_labelDataTimeDigital = lv_label_create(ui_Digital);
    lv_obj_set_width(ui_labelDataTimeDigital, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelDataTimeDigital, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelDataTimeDigital, 54);
    lv_obj_set_y(ui_labelDataTimeDigital, -87);
    lv_obj_set_align(ui_labelDataTimeDigital, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelDataTimeDigital, "0");
    lv_obj_set_style_text_color(ui_labelDataTimeDigital, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelDataTimeDigital, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelDataTimeDigital, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelDataMrpmDigital = lv_label_create(ui_Digital);
    lv_obj_set_width(ui_labelDataMrpmDigital, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelDataMrpmDigital, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelDataMrpmDigital, 54);
    lv_obj_set_y(ui_labelDataMrpmDigital, -30);
    lv_obj_set_align(ui_labelDataMrpmDigital, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelDataMrpmDigital, "0");
    lv_obj_set_style_text_color(ui_labelDataMrpmDigital, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelDataMrpmDigital, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelDataMrpmDigital, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelDataSrpmDigital = lv_label_create(ui_Digital);
    lv_obj_set_width(ui_labelDataSrpmDigital, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelDataSrpmDigital, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelDataSrpmDigital, 54);
    lv_obj_set_y(ui_labelDataSrpmDigital, 27);
    lv_obj_set_align(ui_labelDataSrpmDigital, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelDataSrpmDigital, "0");
    lv_obj_set_style_text_color(ui_labelDataSrpmDigital, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelDataSrpmDigital, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelDataSrpmDigital, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelDataIncDigital = lv_label_create(ui_Digital);
    lv_obj_set_width(ui_labelDataIncDigital, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelDataIncDigital, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelDataIncDigital, 54);
    lv_obj_set_y(ui_labelDataIncDigital, 82);
    lv_obj_set_align(ui_labelDataIncDigital, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelDataIncDigital, "0");
    lv_obj_set_style_text_color(ui_labelDataIncDigital, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelDataIncDigital, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelDataIncDigital, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_buttonStopDigital, ui_event_buttonStopDigital, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonStarDigital, ui_event_buttonStarDigital, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonUpIncDigital, ui_event_buttonUpIncDigital, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonDownIncDigital, ui_event_buttonDownIncDigital, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonUpSrpmDigital, ui_event_buttonUpSrpmDigital, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonDownSrpmDigital, ui_event_buttonDownSrpmDigital, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonHomeDigital, ui_event_buttonHomeDigital, LV_EVENT_ALL, NULL);

}

void ui_Digital_screen_destroy(void)
{
    if(ui_Digital) lv_obj_del(ui_Digital);

    // NULL screen variables
    ui_Digital = NULL;
    ui_bgrDigital = NULL;
    ui_buttonStopDigital = NULL;
    ui_labelStopDigital = NULL;
    ui_buttonStarDigital = NULL;
    ui_labelStartDigital = NULL;
    ui_buttonUpIncDigital = NULL;
    ui_labelUpIncDigital = NULL;
    ui_buttonDownIncDigital = NULL;
    ui_labelDownIncDigital = NULL;
    ui_buttonUpSrpmDigital = NULL;
    ui_labelUpSrpmDigital = NULL;
    ui_buttonDownSrpmDigital = NULL;
    ui_labelDownSrpmDigital = NULL;
    ui_panelPauseDigital = NULL;
    ui_labelPauseDigital = NULL;
    ui_buttonHomeDigital = NULL;
    ui_labelDataTimeDigital = NULL;
    ui_labelDataMrpmDigital = NULL;
    ui_labelDataSrpmDigital = NULL;
    ui_labelDataIncDigital = NULL;

}
