// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: ui_spin_coater

#ifndef UI_DIGITAL_H
#define UI_DIGITAL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Digital
extern void ui_Digital_screen_init(void);
extern void ui_Digital_screen_destroy(void);
extern lv_obj_t * ui_Digital;
extern lv_obj_t * ui_bgrDigital;
extern void ui_event_buttonStopDigital(lv_event_t * e);
extern lv_obj_t * ui_buttonStopDigital;
extern lv_obj_t * ui_labelStopDigital;
extern void ui_event_buttonStarDigital(lv_event_t * e);
extern lv_obj_t * ui_buttonStarDigital;
extern lv_obj_t * ui_labelStartDigital;
extern void ui_event_buttonUpIncDigital(lv_event_t * e);
extern lv_obj_t * ui_buttonUpIncDigital;
extern lv_obj_t * ui_labelUpIncDigital;
extern void ui_event_buttonDownIncDigital(lv_event_t * e);
extern lv_obj_t * ui_buttonDownIncDigital;
extern lv_obj_t * ui_labelDownIncDigital;
extern void ui_event_buttonUpSrpmDigital(lv_event_t * e);
extern lv_obj_t * ui_buttonUpSrpmDigital;
extern lv_obj_t * ui_labelUpSrpmDigital;
extern void ui_event_buttonDownSrpmDigital(lv_event_t * e);
extern lv_obj_t * ui_buttonDownSrpmDigital;
extern lv_obj_t * ui_labelDownSrpmDigital;
extern lv_obj_t * ui_panelPauseDigital;
extern lv_obj_t * ui_labelPauseDigital;
extern void ui_event_buttonHomeDigital(lv_event_t * e);
extern lv_obj_t * ui_buttonHomeDigital;
extern lv_obj_t * ui_labelDataTimeDigital;
extern lv_obj_t * ui_labelDataMrpmDigital;
extern lv_obj_t * ui_labelDataSrpmDigital;
extern lv_obj_t * ui_labelDataIncDigital;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

