// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: ui_spin_coater

#include "ui.h"

lv_obj_t * ui_Home = NULL;
lv_obj_t * ui_bgrHome = NULL;
lv_obj_t * ui_buttonAnalog = NULL;
lv_obj_t * ui_labelAnalog = NULL;
lv_obj_t * ui_buttonDigital = NULL;
lv_obj_t * ui_labelDigital = NULL;
lv_obj_t * ui_buttonRamp = NULL;
lv_obj_t * ui_labelRamp = NULL;
lv_obj_t * ui_buttonSetup = NULL;
lv_obj_t * ui_labelSetup = NULL;
// event funtions
void ui_event_buttonAnalog(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Analog, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Analog_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        Button_Select_Mode_Analog(e);
    }
}

void ui_event_buttonDigital(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Digital, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Digital_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        Button_Select_Mode_Digital(e);
    }
}

void ui_event_buttonRamp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Ramp, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Ramp_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        Button_Select_Mode_Ramp(e);
    }
}

void ui_event_buttonSetup(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Setup, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Setup_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        Button_Select_Mode_Setup(e);
    }
}

// build funtions

void ui_Home_screen_init(void)
{
    ui_Home = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bgrHome = lv_image_create(ui_Home);
    lv_image_set_src(ui_bgrHome, &ui_img_spin_coater_png);
    lv_obj_set_width(ui_bgrHome, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bgrHome, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bgrHome, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bgrHome, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_bgrHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_buttonAnalog = lv_button_create(ui_Home);
    lv_obj_set_width(ui_buttonAnalog, 150);
    lv_obj_set_height(ui_buttonAnalog, 45);
    lv_obj_set_x(ui_buttonAnalog, 94);
    lv_obj_set_y(ui_buttonAnalog, -96);
    lv_obj_set_align(ui_buttonAnalog, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonAnalog, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonAnalog, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonAnalog, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonAnalog, lv_color_hex(0x9CA3AF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonAnalog, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_buttonAnalog, lv_color_hex(0x545454), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_buttonAnalog, 170, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_buttonAnalog, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_buttonAnalog, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelAnalog = lv_label_create(ui_buttonAnalog);
    lv_obj_set_width(ui_labelAnalog, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelAnalog, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelAnalog, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelAnalog, "ANALOG");
    lv_obj_set_style_text_color(ui_labelAnalog, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelAnalog, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelAnalog, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonDigital = lv_button_create(ui_Home);
    lv_obj_set_width(ui_buttonDigital, 150);
    lv_obj_set_height(ui_buttonDigital, 45);
    lv_obj_set_x(ui_buttonDigital, 94);
    lv_obj_set_y(ui_buttonDigital, -33);
    lv_obj_set_align(ui_buttonDigital, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonDigital, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonDigital, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonDigital, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonDigital, lv_color_hex(0x9CA3AF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonDigital, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_buttonDigital, lv_color_hex(0x545454), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_buttonDigital, 170, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_buttonDigital, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_buttonDigital, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelDigital = lv_label_create(ui_buttonDigital);
    lv_obj_set_width(ui_labelDigital, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelDigital, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelDigital, -5);
    lv_obj_set_y(ui_labelDigital, 0);
    lv_obj_set_align(ui_labelDigital, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelDigital, "DIGITAL");
    lv_obj_set_style_text_color(ui_labelDigital, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelDigital, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelDigital, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonRamp = lv_button_create(ui_Home);
    lv_obj_set_width(ui_buttonRamp, 150);
    lv_obj_set_height(ui_buttonRamp, 45);
    lv_obj_set_x(ui_buttonRamp, 94);
    lv_obj_set_y(ui_buttonRamp, 29);
    lv_obj_set_align(ui_buttonRamp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonRamp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonRamp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonRamp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonRamp, lv_color_hex(0x9CA3AF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonRamp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_buttonRamp, lv_color_hex(0x545454), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_buttonRamp, 170, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_buttonRamp, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_buttonRamp, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelRamp = lv_label_create(ui_buttonRamp);
    lv_obj_set_width(ui_labelRamp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelRamp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelRamp, -15);
    lv_obj_set_y(ui_labelRamp, 0);
    lv_obj_set_align(ui_labelRamp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelRamp, "RAMP");
    lv_obj_set_style_text_color(ui_labelRamp, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelRamp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelRamp, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonSetup = lv_button_create(ui_Home);
    lv_obj_set_width(ui_buttonSetup, 150);
    lv_obj_set_height(ui_buttonSetup, 45);
    lv_obj_set_x(ui_buttonSetup, 94);
    lv_obj_set_y(ui_buttonSetup, 94);
    lv_obj_set_align(ui_buttonSetup, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonSetup, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonSetup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonSetup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonSetup, lv_color_hex(0x9CA3AF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonSetup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_buttonSetup, lv_color_hex(0x545454), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_buttonSetup, 170, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_buttonSetup, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_buttonSetup, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelSetup = lv_label_create(ui_buttonSetup);
    lv_obj_set_width(ui_labelSetup, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelSetup, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelSetup, -11);
    lv_obj_set_y(ui_labelSetup, 0);
    lv_obj_set_align(ui_labelSetup, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelSetup, "SETUP");
    lv_obj_set_style_text_color(ui_labelSetup, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelSetup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelSetup, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_buttonAnalog, ui_event_buttonAnalog, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonDigital, ui_event_buttonDigital, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonRamp, ui_event_buttonRamp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonSetup, ui_event_buttonSetup, LV_EVENT_ALL, NULL);

}

void ui_Home_screen_destroy(void)
{
    if(ui_Home) lv_obj_del(ui_Home);

    // NULL screen variables
    ui_Home = NULL;
    ui_bgrHome = NULL;
    ui_buttonAnalog = NULL;
    ui_labelAnalog = NULL;
    ui_buttonDigital = NULL;
    ui_labelDigital = NULL;
    ui_buttonRamp = NULL;
    ui_labelRamp = NULL;
    ui_buttonSetup = NULL;
    ui_labelSetup = NULL;

}
