// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: ui_spin_coater

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Home
extern void ui_Home_screen_init(void);
extern void ui_Home_screen_destroy(void);
extern lv_obj_t * ui_Home;
extern lv_obj_t * ui_bgrHome;
extern void ui_event_buttonAnalog(lv_event_t * e);
extern lv_obj_t * ui_buttonAnalog;
extern lv_obj_t * ui_labelAnalog;
extern void ui_event_buttonDigital(lv_event_t * e);
extern lv_obj_t * ui_buttonDigital;
extern lv_obj_t * ui_labelDigital;
extern void ui_event_buttonRamp(lv_event_t * e);
extern lv_obj_t * ui_buttonRamp;
extern lv_obj_t * ui_labelRamp;
extern void ui_event_buttonSetup(lv_event_t * e);
extern lv_obj_t * ui_buttonSetup;
extern lv_obj_t * ui_labelSetup;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

