// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: ui_spin_coater

#ifndef UI_RAMP_H
#define UI_RAMP_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Ramp
extern void ui_Ramp_screen_init(void);
extern void ui_Ramp_screen_destroy(void);
extern lv_obj_t * ui_Ramp;
extern lv_obj_t * ui_bgrRamp;
extern void ui_event_buttonStopRamp(lv_event_t * e);
extern lv_obj_t * ui_buttonStopRamp;
extern lv_obj_t * ui_labelStopRamp;
extern void ui_event_buttonStarRamp(lv_event_t * e);
extern lv_obj_t * ui_buttonStarRamp;
extern lv_obj_t * ui_labelStartRamp;
extern lv_obj_t * ui_panelPauseRamp;
extern lv_obj_t * ui_labelPauseRamp;
extern void ui_event_buttonHomeRamp(lv_event_t * e);
extern lv_obj_t * ui_buttonHomeRamp;
extern lv_obj_t * ui_labelDataMaxSpeedRampMode;
extern lv_obj_t * ui_labelDataMaxTimeRampMode;
extern lv_obj_t * ui_labelDataMinSpeedRampMode;
extern lv_obj_t * ui_labelDataMinTimeRampMode;
extern lv_obj_t * ui_labelDataRpmRampMode;
extern void ui_event_buttonRampMode1(lv_event_t * e);
extern lv_obj_t * ui_buttonRampMode1;
extern lv_obj_t * ui_labelRampMode1;
extern void ui_event_buttonRampMode2(lv_event_t * e);
extern lv_obj_t * ui_buttonRampMode2;
extern lv_obj_t * ui_labelRampMode2;
extern void ui_event_buttonRampMode3(lv_event_t * e);
extern lv_obj_t * ui_buttonRampMode3;
extern lv_obj_t * ui_labelRampMode3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

