// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: ui_spin_coater

#include "ui.h"

lv_obj_t * ui_Ramp = NULL;
lv_obj_t * ui_bgrRamp = NULL;
lv_obj_t * ui_buttonStopRamp = NULL;
lv_obj_t * ui_labelStopRamp = NULL;
lv_obj_t * ui_buttonStarRamp = NULL;
lv_obj_t * ui_labelStartRamp = NULL;
lv_obj_t * ui_panelPauseRamp = NULL;
lv_obj_t * ui_labelPauseRamp = NULL;
lv_obj_t * ui_buttonHomeRamp = NULL;
lv_obj_t * ui_labelDataMaxSpeedRampMode = NULL;
lv_obj_t * ui_labelDataMaxTimeRampMode = NULL;
lv_obj_t * ui_labelDataMinSpeedRampMode = NULL;
lv_obj_t * ui_labelDataMinTimeRampMode = NULL;
lv_obj_t * ui_labelDataRpmRampMode = NULL;
lv_obj_t * ui_buttonRampMode1 = NULL;
lv_obj_t * ui_labelRampMode1 = NULL;
lv_obj_t * ui_buttonRampMode2 = NULL;
lv_obj_t * ui_labelRampMode2 = NULL;
lv_obj_t * ui_buttonRampMode3 = NULL;
lv_obj_t * ui_labelRampMode3 = NULL;
// event funtions
void ui_event_buttonStopRamp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Button_StopRamp(e);
    }
}

void ui_event_buttonStarRamp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Button_StartRamp(e);
    }
}

void ui_event_buttonHomeRamp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Home_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        Button_SetStateIDLE_Ramp(e);
    }
}

void ui_event_buttonRampMode1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Button_Select_Mode1_Ramp(e);
    }
}

void ui_event_buttonRampMode2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Button_Select_Mode2_Ramp(e);
    }
}

void ui_event_buttonRampMode3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Button_Select_Mode3_Ramp(e);
    }
}

// build funtions

void ui_Ramp_screen_init(void)
{
    ui_Ramp = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Ramp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bgrRamp = lv_image_create(ui_Ramp);
    lv_image_set_src(ui_bgrRamp, &ui_img_rampscreen_png);
    lv_obj_set_width(ui_bgrRamp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bgrRamp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bgrRamp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bgrRamp, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_bgrRamp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_buttonStopRamp = lv_button_create(ui_Ramp);
    lv_obj_set_width(ui_buttonStopRamp, 160);
    lv_obj_set_height(ui_buttonStopRamp, 50);
    lv_obj_set_x(ui_buttonStopRamp, -160);
    lv_obj_set_y(ui_buttonStopRamp, 135);
    lv_obj_set_align(ui_buttonStopRamp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonStopRamp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonStopRamp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonStopRamp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonStopRamp, lv_color_hex(0xE64A4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonStopRamp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelStopRamp = lv_label_create(ui_buttonStopRamp);
    lv_obj_set_width(ui_labelStopRamp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelStopRamp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelStopRamp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelStopRamp, "STOP");
    lv_obj_set_style_text_color(ui_labelStopRamp, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelStopRamp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelStopRamp, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonStarRamp = lv_button_create(ui_Ramp);
    lv_obj_set_width(ui_buttonStarRamp, 160);
    lv_obj_set_height(ui_buttonStarRamp, 50);
    lv_obj_set_x(ui_buttonStarRamp, 160);
    lv_obj_set_y(ui_buttonStarRamp, 135);
    lv_obj_set_align(ui_buttonStarRamp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonStarRamp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonStarRamp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonStarRamp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonStarRamp, lv_color_hex(0x10B981), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonStarRamp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelStartRamp = lv_label_create(ui_buttonStarRamp);
    lv_obj_set_width(ui_labelStartRamp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelStartRamp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelStartRamp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelStartRamp, "START");
    lv_obj_set_style_text_color(ui_labelStartRamp, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelStartRamp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelStartRamp, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panelPauseRamp = lv_obj_create(ui_Ramp);
    lv_obj_set_width(ui_panelPauseRamp, 160);
    lv_obj_set_height(ui_panelPauseRamp, 50);
    lv_obj_set_x(ui_panelPauseRamp, 0);
    lv_obj_set_y(ui_panelPauseRamp, 135);
    lv_obj_set_align(ui_panelPauseRamp, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panelPauseRamp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panelPauseRamp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panelPauseRamp, lv_color_hex(0x9CA3AF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelPauseRamp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panelPauseRamp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panelPauseRamp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_panelPauseRamp, lv_color_hex(0x9CA3AF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_panelPauseRamp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_panelPauseRamp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_panelPauseRamp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelPauseRamp = lv_label_create(ui_panelPauseRamp);
    lv_obj_set_width(ui_labelPauseRamp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelPauseRamp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelPauseRamp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelPauseRamp, "PAUSE");
    lv_obj_set_style_text_color(ui_labelPauseRamp, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelPauseRamp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelPauseRamp, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonHomeRamp = lv_imagebutton_create(ui_Ramp);
    lv_imagebutton_set_src(ui_buttonHomeRamp, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_670667251, NULL);
    lv_imagebutton_set_src(ui_buttonHomeRamp, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_670667251, NULL);
    lv_obj_set_width(ui_buttonHomeRamp, 40);
    lv_obj_set_height(ui_buttonHomeRamp, 40);
    lv_obj_set_x(ui_buttonHomeRamp, -213);
    lv_obj_set_y(ui_buttonHomeRamp, -136);
    lv_obj_set_align(ui_buttonHomeRamp, LV_ALIGN_CENTER);

    ui_labelDataMaxSpeedRampMode = lv_label_create(ui_Ramp);
    lv_obj_set_width(ui_labelDataMaxSpeedRampMode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelDataMaxSpeedRampMode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelDataMaxSpeedRampMode, -75);
    lv_obj_set_y(ui_labelDataMaxSpeedRampMode, -45);
    lv_obj_set_align(ui_labelDataMaxSpeedRampMode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelDataMaxSpeedRampMode, "0");
    lv_obj_set_style_text_color(ui_labelDataMaxSpeedRampMode, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelDataMaxSpeedRampMode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelDataMaxSpeedRampMode, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelDataMaxTimeRampMode = lv_label_create(ui_Ramp);
    lv_obj_set_width(ui_labelDataMaxTimeRampMode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelDataMaxTimeRampMode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelDataMaxTimeRampMode, 86);
    lv_obj_set_y(ui_labelDataMaxTimeRampMode, -45);
    lv_obj_set_align(ui_labelDataMaxTimeRampMode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelDataMaxTimeRampMode, "0");
    lv_obj_set_style_text_color(ui_labelDataMaxTimeRampMode, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelDataMaxTimeRampMode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelDataMaxTimeRampMode, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelDataMinSpeedRampMode = lv_label_create(ui_Ramp);
    lv_obj_set_width(ui_labelDataMinSpeedRampMode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelDataMinSpeedRampMode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelDataMinSpeedRampMode, -75);
    lv_obj_set_y(ui_labelDataMinSpeedRampMode, 12);
    lv_obj_set_align(ui_labelDataMinSpeedRampMode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelDataMinSpeedRampMode, "0");
    lv_obj_set_style_text_color(ui_labelDataMinSpeedRampMode, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelDataMinSpeedRampMode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelDataMinSpeedRampMode, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelDataMinTimeRampMode = lv_label_create(ui_Ramp);
    lv_obj_set_width(ui_labelDataMinTimeRampMode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelDataMinTimeRampMode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelDataMinTimeRampMode, 86);
    lv_obj_set_y(ui_labelDataMinTimeRampMode, 12);
    lv_obj_set_align(ui_labelDataMinTimeRampMode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelDataMinTimeRampMode, "0");
    lv_obj_set_style_text_color(ui_labelDataMinTimeRampMode, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelDataMinTimeRampMode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelDataMinTimeRampMode, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelDataRpmRampMode = lv_label_create(ui_Ramp);
    lv_obj_set_width(ui_labelDataRpmRampMode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelDataRpmRampMode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelDataRpmRampMode, -75);
    lv_obj_set_y(ui_labelDataRpmRampMode, 73);
    lv_obj_set_align(ui_labelDataRpmRampMode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelDataRpmRampMode, "0");
    lv_obj_set_style_text_color(ui_labelDataRpmRampMode, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelDataRpmRampMode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelDataRpmRampMode, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonRampMode1 = lv_button_create(ui_Ramp);
    lv_obj_set_width(ui_buttonRampMode1, 43);
    lv_obj_set_height(ui_buttonRampMode1, 43);
    lv_obj_set_x(ui_buttonRampMode1, -57);
    lv_obj_set_y(ui_buttonRampMode1, -89);
    lv_obj_set_align(ui_buttonRampMode1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonRampMode1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonRampMode1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonRampMode1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonRampMode1, lv_color_hex(0xF2F2F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonRampMode1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_buttonRampMode1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_buttonRampMode1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelRampMode1 = lv_label_create(ui_buttonRampMode1);
    lv_obj_set_width(ui_labelRampMode1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelRampMode1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelRampMode1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelRampMode1, "1");
    lv_obj_set_style_text_color(ui_labelRampMode1, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelRampMode1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelRampMode1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonRampMode2 = lv_button_create(ui_Ramp);
    lv_obj_set_width(ui_buttonRampMode2, 43);
    lv_obj_set_height(ui_buttonRampMode2, 43);
    lv_obj_set_x(ui_buttonRampMode2, -7);
    lv_obj_set_y(ui_buttonRampMode2, -89);
    lv_obj_set_align(ui_buttonRampMode2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonRampMode2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonRampMode2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonRampMode2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonRampMode2, lv_color_hex(0xF2F2F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonRampMode2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_buttonRampMode2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_buttonRampMode2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelRampMode2 = lv_label_create(ui_buttonRampMode2);
    lv_obj_set_width(ui_labelRampMode2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelRampMode2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelRampMode2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelRampMode2, "2");
    lv_obj_set_style_text_color(ui_labelRampMode2, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelRampMode2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelRampMode2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonRampMode3 = lv_button_create(ui_Ramp);
    lv_obj_set_width(ui_buttonRampMode3, 43);
    lv_obj_set_height(ui_buttonRampMode3, 43);
    lv_obj_set_x(ui_buttonRampMode3, 43);
    lv_obj_set_y(ui_buttonRampMode3, -89);
    lv_obj_set_align(ui_buttonRampMode3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonRampMode3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonRampMode3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonRampMode3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonRampMode3, lv_color_hex(0xF2F2F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonRampMode3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_buttonRampMode3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_buttonRampMode3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelRampMode3 = lv_label_create(ui_buttonRampMode3);
    lv_obj_set_width(ui_labelRampMode3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelRampMode3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelRampMode3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelRampMode3, "3");
    lv_obj_set_style_text_color(ui_labelRampMode3, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelRampMode3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelRampMode3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_buttonStopRamp, ui_event_buttonStopRamp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonStarRamp, ui_event_buttonStarRamp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonHomeRamp, ui_event_buttonHomeRamp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonRampMode1, ui_event_buttonRampMode1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonRampMode2, ui_event_buttonRampMode2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonRampMode3, ui_event_buttonRampMode3, LV_EVENT_ALL, NULL);

}

void ui_Ramp_screen_destroy(void)
{
    if(ui_Ramp) lv_obj_del(ui_Ramp);

    // NULL screen variables
    ui_Ramp = NULL;
    ui_bgrRamp = NULL;
    ui_buttonStopRamp = NULL;
    ui_labelStopRamp = NULL;
    ui_buttonStarRamp = NULL;
    ui_labelStartRamp = NULL;
    ui_panelPauseRamp = NULL;
    ui_labelPauseRamp = NULL;
    ui_buttonHomeRamp = NULL;
    ui_labelDataMaxSpeedRampMode = NULL;
    ui_labelDataMaxTimeRampMode = NULL;
    ui_labelDataMinSpeedRampMode = NULL;
    ui_labelDataMinTimeRampMode = NULL;
    ui_labelDataRpmRampMode = NULL;
    ui_buttonRampMode1 = NULL;
    ui_labelRampMode1 = NULL;
    ui_buttonRampMode2 = NULL;
    ui_labelRampMode2 = NULL;
    ui_buttonRampMode3 = NULL;
    ui_labelRampMode3 = NULL;

}
