// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: ui_spin_coater

#include "ui.h"

lv_obj_t * ui_Setup = NULL;
lv_obj_t * ui_bgrSetup = NULL;
lv_obj_t * ui_buttonSetupReset = NULL;
lv_obj_t * ui_labelSetupReset = NULL;
lv_obj_t * ui_buttonSetupRamp = NULL;
lv_obj_t * ui_labelSetupRamp = NULL;
lv_obj_t * ui_buttonSetupAbout = NULL;
lv_obj_t * ui_labelSetupAbout = NULL;
lv_obj_t * ui_buttonHomeSetup = NULL;
// event funtions
void ui_event_buttonSetupRamp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SetupRamp, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SetupRamp_screen_init);
    }
}

void ui_event_buttonHomeSetup(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Home_screen_init);
    }
}

// build funtions

void ui_Setup_screen_init(void)
{
    ui_Setup = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Setup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bgrSetup = lv_image_create(ui_Setup);
    lv_image_set_src(ui_bgrSetup, &ui_img_setupscreen_png);
    lv_obj_set_width(ui_bgrSetup, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bgrSetup, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bgrSetup, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bgrSetup, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_bgrSetup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_buttonSetupReset = lv_button_create(ui_Setup);
    lv_obj_set_width(ui_buttonSetupReset, 150);
    lv_obj_set_height(ui_buttonSetupReset, 45);
    lv_obj_set_x(ui_buttonSetupReset, 0);
    lv_obj_set_y(ui_buttonSetupReset, -58);
    lv_obj_set_align(ui_buttonSetupReset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonSetupReset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonSetupReset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonSetupReset, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonSetupReset, lv_color_hex(0x9CA3AF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonSetupReset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_buttonSetupReset, lv_color_hex(0x545454), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_buttonSetupReset, 170, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_buttonSetupReset, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_buttonSetupReset, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelSetupReset = lv_label_create(ui_buttonSetupReset);
    lv_obj_set_width(ui_labelSetupReset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelSetupReset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelSetupReset, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelSetupReset, "RESET");
    lv_obj_set_style_text_color(ui_labelSetupReset, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelSetupReset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelSetupReset, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonSetupRamp = lv_button_create(ui_Setup);
    lv_obj_set_width(ui_buttonSetupRamp, 150);
    lv_obj_set_height(ui_buttonSetupRamp, 45);
    lv_obj_set_x(ui_buttonSetupRamp, 0);
    lv_obj_set_y(ui_buttonSetupRamp, 12);
    lv_obj_set_align(ui_buttonSetupRamp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonSetupRamp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonSetupRamp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonSetupRamp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonSetupRamp, lv_color_hex(0x9CA3AF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonSetupRamp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_buttonSetupRamp, lv_color_hex(0x545454), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_buttonSetupRamp, 170, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_buttonSetupRamp, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_buttonSetupRamp, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelSetupRamp = lv_label_create(ui_buttonSetupRamp);
    lv_obj_set_width(ui_labelSetupRamp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelSetupRamp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelSetupRamp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelSetupRamp, "RAMP");
    lv_obj_set_style_text_color(ui_labelSetupRamp, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelSetupRamp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelSetupRamp, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonSetupAbout = lv_button_create(ui_Setup);
    lv_obj_set_width(ui_buttonSetupAbout, 150);
    lv_obj_set_height(ui_buttonSetupAbout, 45);
    lv_obj_set_x(ui_buttonSetupAbout, 0);
    lv_obj_set_y(ui_buttonSetupAbout, 81);
    lv_obj_set_align(ui_buttonSetupAbout, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonSetupAbout, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonSetupAbout, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonSetupAbout, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonSetupAbout, lv_color_hex(0x9CA3AF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonSetupAbout, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_buttonSetupAbout, lv_color_hex(0x545454), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_buttonSetupAbout, 170, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_buttonSetupAbout, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_buttonSetupAbout, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelSetupAbout = lv_label_create(ui_buttonSetupAbout);
    lv_obj_set_width(ui_labelSetupAbout, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelSetupAbout, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelSetupAbout, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelSetupAbout, "ABOUT");
    lv_obj_set_style_text_color(ui_labelSetupAbout, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelSetupAbout, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelSetupAbout, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonHomeSetup = lv_imagebutton_create(ui_Setup);
    lv_imagebutton_set_src(ui_buttonHomeSetup, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_home_png, NULL);
    lv_imagebutton_set_src(ui_buttonHomeSetup, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_home_png, NULL);
    lv_obj_set_width(ui_buttonHomeSetup, 30);
    lv_obj_set_height(ui_buttonHomeSetup, 30);
    lv_obj_set_x(ui_buttonHomeSetup, -183);
    lv_obj_set_y(ui_buttonHomeSetup, -123);
    lv_obj_set_align(ui_buttonHomeSetup, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_buttonSetupRamp, ui_event_buttonSetupRamp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonHomeSetup, ui_event_buttonHomeSetup, LV_EVENT_ALL, NULL);

}

void ui_Setup_screen_destroy(void)
{
    if(ui_Setup) lv_obj_del(ui_Setup);

    // NULL screen variables
    ui_Setup = NULL;
    ui_bgrSetup = NULL;
    ui_buttonSetupReset = NULL;
    ui_labelSetupReset = NULL;
    ui_buttonSetupRamp = NULL;
    ui_labelSetupRamp = NULL;
    ui_buttonSetupAbout = NULL;
    ui_labelSetupAbout = NULL;
    ui_buttonHomeSetup = NULL;

}
