// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: ui_spin_coater

#ifndef UI_SETUP_H
#define UI_SETUP_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Setup
extern void ui_Setup_screen_init(void);
extern void ui_Setup_screen_destroy(void);
extern lv_obj_t * ui_Setup;
extern lv_obj_t * ui_bgrSetup;
extern lv_obj_t * ui_buttonSetupReset;
extern lv_obj_t * ui_labelSetupReset;
extern void ui_event_buttonSetupRamp(lv_event_t * e);
extern lv_obj_t * ui_buttonSetupRamp;
extern lv_obj_t * ui_labelSetupRamp;
extern lv_obj_t * ui_buttonSetupAbout;
extern lv_obj_t * ui_labelSetupAbout;
extern void ui_event_buttonHomeSetup(lv_event_t * e);
extern lv_obj_t * ui_buttonHomeSetup;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

