// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: ui_spin_coater

#include "ui.h"

lv_obj_t * ui_SetupRamp = NULL;
lv_obj_t * ui_bgrSetupRamp = NULL;
lv_obj_t * ui_buttonHomeSetupRamp = NULL;
lv_obj_t * ui_buttonSetupRampMode1 = NULL;
lv_obj_t * ui_labelSetupRampMode1 = NULL;
lv_obj_t * ui_buttonSetupRampMode2 = NULL;
lv_obj_t * ui_labelSetupRampMode2 = NULL;
lv_obj_t * ui_buttonSetupRampMode3 = NULL;
lv_obj_t * ui_labelSetupRampMode3 = NULL;
lv_obj_t * ui_buttonDownRmpMinSetup = NULL;
lv_obj_t * ui_labelDownRmpMinSetup = NULL;
lv_obj_t * ui_buttonUpRmpMinSetup = NULL;
lv_obj_t * ui_labelUpRmpMinSetup = NULL;
lv_obj_t * ui_buttonUpTimeMinSetup = NULL;
lv_obj_t * ui_labelUpTimeMinSetup = NULL;
lv_obj_t * ui_buttonDownTimeMinSetup = NULL;
lv_obj_t * ui_labelDownTimeMinSetup = NULL;
lv_obj_t * ui_buttonUpRmpMaxSetup = NULL;
lv_obj_t * ui_labelUpRmpMaxSetup = NULL;
lv_obj_t * ui_buttonUpTimeMaxSetup = NULL;
lv_obj_t * ui_labelUpTimeMaxSetup = NULL;
lv_obj_t * ui_buttonDownRmpMaxSetup = NULL;
lv_obj_t * ui_labelDownRmpMaxSetup = NULL;
lv_obj_t * ui_buttonDownTimeMaxSetup = NULL;
lv_obj_t * ui_labelDownTimeMaxSetup = NULL;
lv_obj_t * ui_buttonSaveSetupRamp = NULL;
lv_obj_t * ui_labelSaveSetupRamp = NULL;
lv_obj_t * ui_buttonResetSetupRamp = NULL;
lv_obj_t * ui_labelResetSetupRamp = NULL;
lv_obj_t * ui_labelDataMinSpeed = NULL;
lv_obj_t * ui_labelDataMinTime = NULL;
lv_obj_t * ui_labelDataMaxSpeed = NULL;
lv_obj_t * ui_labelDataMaxTime = NULL;
// event funtions
void ui_event_buttonHomeSetupRamp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Home_screen_init);
    }
}

void ui_event_buttonSetupRampMode1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Button_Select_Mode1_Setup(e);
    }
}

void ui_event_buttonSetupRampMode2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Button_Select_Mode2_Setup(e);
    }
}

void ui_event_buttonSetupRampMode3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Button_Select_Mode3_Setup(e);
    }
}

void ui_event_buttonDownRmpMinSetup(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Button_Down_Min_Speed(e);
    }
}

void ui_event_buttonUpRmpMinSetup(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Button_Up_Min_Speed(e);
    }
}

void ui_event_buttonUpTimeMinSetup(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Button_Up_Min_Time(e);
    }
}

void ui_event_buttonDownTimeMinSetup(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Button_Down_Min_Time(e);
    }
}

void ui_event_buttonUpRmpMaxSetup(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Button_Up_Max_Speed(e);
    }
}

void ui_event_buttonUpTimeMaxSetup(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Button_Up_Max_Time(e);
    }
}

void ui_event_buttonDownRmpMaxSetup(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Button_Down_Max_Speed(e);
    }
}

void ui_event_buttonDownTimeMaxSetup(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Button_Down_Max_Time(e);
    }
}

void ui_event_buttonSaveSetupRamp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Button_Save_Setup_Ramp(e);
    }
}

void ui_event_buttonResetSetupRamp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Button_Reset_Setup_Ramp(e);
    }
}

// build funtions

void ui_SetupRamp_screen_init(void)
{
    ui_SetupRamp = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SetupRamp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bgrSetupRamp = lv_image_create(ui_SetupRamp);
    lv_image_set_src(ui_bgrSetupRamp, &ui_img_setuprampscreen_png);
    lv_obj_set_width(ui_bgrSetupRamp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bgrSetupRamp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bgrSetupRamp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bgrSetupRamp, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_bgrSetupRamp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_buttonHomeSetupRamp = lv_imagebutton_create(ui_SetupRamp);
    lv_imagebutton_set_src(ui_buttonHomeSetupRamp, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_670667251, NULL);
    lv_imagebutton_set_src(ui_buttonHomeSetupRamp, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_670667251, NULL);
    lv_obj_set_width(ui_buttonHomeSetupRamp, 40);
    lv_obj_set_height(ui_buttonHomeSetupRamp, 40);
    lv_obj_set_x(ui_buttonHomeSetupRamp, -213);
    lv_obj_set_y(ui_buttonHomeSetupRamp, -136);
    lv_obj_set_align(ui_buttonHomeSetupRamp, LV_ALIGN_CENTER);

    ui_buttonSetupRampMode1 = lv_button_create(ui_SetupRamp);
    lv_obj_set_width(ui_buttonSetupRampMode1, 43);
    lv_obj_set_height(ui_buttonSetupRampMode1, 43);
    lv_obj_set_x(ui_buttonSetupRampMode1, -73);
    lv_obj_set_y(ui_buttonSetupRampMode1, 130);
    lv_obj_set_align(ui_buttonSetupRampMode1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonSetupRampMode1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonSetupRampMode1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonSetupRampMode1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonSetupRampMode1, lv_color_hex(0xF2F2F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonSetupRampMode1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_buttonSetupRampMode1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_buttonSetupRampMode1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelSetupRampMode1 = lv_label_create(ui_buttonSetupRampMode1);
    lv_obj_set_width(ui_labelSetupRampMode1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelSetupRampMode1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelSetupRampMode1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelSetupRampMode1, "1");
    lv_obj_set_style_text_color(ui_labelSetupRampMode1, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelSetupRampMode1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelSetupRampMode1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonSetupRampMode2 = lv_button_create(ui_SetupRamp);
    lv_obj_set_width(ui_buttonSetupRampMode2, 43);
    lv_obj_set_height(ui_buttonSetupRampMode2, 43);
    lv_obj_set_x(ui_buttonSetupRampMode2, -20);
    lv_obj_set_y(ui_buttonSetupRampMode2, 130);
    lv_obj_set_align(ui_buttonSetupRampMode2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonSetupRampMode2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonSetupRampMode2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonSetupRampMode2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonSetupRampMode2, lv_color_hex(0xF2F2F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonSetupRampMode2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_buttonSetupRampMode2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_buttonSetupRampMode2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelSetupRampMode2 = lv_label_create(ui_buttonSetupRampMode2);
    lv_obj_set_width(ui_labelSetupRampMode2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelSetupRampMode2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelSetupRampMode2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelSetupRampMode2, "2");
    lv_obj_set_style_text_color(ui_labelSetupRampMode2, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelSetupRampMode2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelSetupRampMode2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonSetupRampMode3 = lv_button_create(ui_SetupRamp);
    lv_obj_set_width(ui_buttonSetupRampMode3, 43);
    lv_obj_set_height(ui_buttonSetupRampMode3, 43);
    lv_obj_set_x(ui_buttonSetupRampMode3, 34);
    lv_obj_set_y(ui_buttonSetupRampMode3, 130);
    lv_obj_set_align(ui_buttonSetupRampMode3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonSetupRampMode3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonSetupRampMode3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonSetupRampMode3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonSetupRampMode3, lv_color_hex(0xF2F2F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonSetupRampMode3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_buttonSetupRampMode3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_buttonSetupRampMode3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelSetupRampMode3 = lv_label_create(ui_buttonSetupRampMode3);
    lv_obj_set_width(ui_labelSetupRampMode3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelSetupRampMode3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelSetupRampMode3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelSetupRampMode3, "3");
    lv_obj_set_style_text_color(ui_labelSetupRampMode3, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelSetupRampMode3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelSetupRampMode3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonDownRmpMinSetup = lv_button_create(ui_SetupRamp);
    lv_obj_set_width(ui_buttonDownRmpMinSetup, 60);
    lv_obj_set_height(ui_buttonDownRmpMinSetup, 40);
    lv_obj_set_x(ui_buttonDownRmpMinSetup, 129);
    lv_obj_set_y(ui_buttonDownRmpMinSetup, -86);
    lv_obj_set_align(ui_buttonDownRmpMinSetup, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonDownRmpMinSetup, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonDownRmpMinSetup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonDownRmpMinSetup, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonDownRmpMinSetup, lv_color_hex(0xD1D5DB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonDownRmpMinSetup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_buttonDownRmpMinSetup, lv_color_hex(0x231F20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_buttonDownRmpMinSetup, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_buttonDownRmpMinSetup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_buttonDownRmpMinSetup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelDownRmpMinSetup = lv_label_create(ui_buttonDownRmpMinSetup);
    lv_obj_set_width(ui_labelDownRmpMinSetup, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelDownRmpMinSetup, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelDownRmpMinSetup, 0);
    lv_obj_set_y(ui_labelDownRmpMinSetup, -3);
    lv_obj_set_align(ui_labelDownRmpMinSetup, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelDownRmpMinSetup, "-");
    lv_obj_set_style_text_color(ui_labelDownRmpMinSetup, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelDownRmpMinSetup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelDownRmpMinSetup, &ui_font_MonterLight48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonUpRmpMinSetup = lv_button_create(ui_SetupRamp);
    lv_obj_set_width(ui_buttonUpRmpMinSetup, 60);
    lv_obj_set_height(ui_buttonUpRmpMinSetup, 40);
    lv_obj_set_x(ui_buttonUpRmpMinSetup, 200);
    lv_obj_set_y(ui_buttonUpRmpMinSetup, -86);
    lv_obj_set_align(ui_buttonUpRmpMinSetup, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonUpRmpMinSetup, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonUpRmpMinSetup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonUpRmpMinSetup, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonUpRmpMinSetup, lv_color_hex(0xD1D5DB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonUpRmpMinSetup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_buttonUpRmpMinSetup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_buttonUpRmpMinSetup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelUpRmpMinSetup = lv_label_create(ui_buttonUpRmpMinSetup);
    lv_obj_set_width(ui_labelUpRmpMinSetup, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelUpRmpMinSetup, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelUpRmpMinSetup, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelUpRmpMinSetup, "+");
    lv_obj_set_style_text_color(ui_labelUpRmpMinSetup, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelUpRmpMinSetup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelUpRmpMinSetup, &ui_font_MonterLight36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonUpTimeMinSetup = lv_button_create(ui_SetupRamp);
    lv_obj_set_width(ui_buttonUpTimeMinSetup, 60);
    lv_obj_set_height(ui_buttonUpTimeMinSetup, 40);
    lv_obj_set_x(ui_buttonUpTimeMinSetup, 200);
    lv_obj_set_y(ui_buttonUpTimeMinSetup, -34);
    lv_obj_set_align(ui_buttonUpTimeMinSetup, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonUpTimeMinSetup, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonUpTimeMinSetup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonUpTimeMinSetup, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonUpTimeMinSetup, lv_color_hex(0xD1D5DB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonUpTimeMinSetup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_buttonUpTimeMinSetup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_buttonUpTimeMinSetup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelUpTimeMinSetup = lv_label_create(ui_buttonUpTimeMinSetup);
    lv_obj_set_width(ui_labelUpTimeMinSetup, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelUpTimeMinSetup, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelUpTimeMinSetup, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelUpTimeMinSetup, "+");
    lv_obj_set_style_text_color(ui_labelUpTimeMinSetup, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelUpTimeMinSetup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelUpTimeMinSetup, &ui_font_MonterLight36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonDownTimeMinSetup = lv_button_create(ui_SetupRamp);
    lv_obj_set_width(ui_buttonDownTimeMinSetup, 60);
    lv_obj_set_height(ui_buttonDownTimeMinSetup, 40);
    lv_obj_set_x(ui_buttonDownTimeMinSetup, 129);
    lv_obj_set_y(ui_buttonDownTimeMinSetup, -34);
    lv_obj_set_align(ui_buttonDownTimeMinSetup, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonDownTimeMinSetup, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonDownTimeMinSetup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonDownTimeMinSetup, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonDownTimeMinSetup, lv_color_hex(0xD1D5DB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonDownTimeMinSetup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_buttonDownTimeMinSetup, lv_color_hex(0x231F20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_buttonDownTimeMinSetup, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_buttonDownTimeMinSetup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_buttonDownTimeMinSetup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelDownTimeMinSetup = lv_label_create(ui_buttonDownTimeMinSetup);
    lv_obj_set_width(ui_labelDownTimeMinSetup, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelDownTimeMinSetup, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelDownTimeMinSetup, 0);
    lv_obj_set_y(ui_labelDownTimeMinSetup, -3);
    lv_obj_set_align(ui_labelDownTimeMinSetup, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelDownTimeMinSetup, "-");
    lv_obj_set_style_text_color(ui_labelDownTimeMinSetup, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelDownTimeMinSetup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelDownTimeMinSetup, &ui_font_MonterLight48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonUpRmpMaxSetup = lv_button_create(ui_SetupRamp);
    lv_obj_set_width(ui_buttonUpRmpMaxSetup, 60);
    lv_obj_set_height(ui_buttonUpRmpMaxSetup, 40);
    lv_obj_set_x(ui_buttonUpRmpMaxSetup, 200);
    lv_obj_set_y(ui_buttonUpRmpMaxSetup, 18);
    lv_obj_set_align(ui_buttonUpRmpMaxSetup, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonUpRmpMaxSetup, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonUpRmpMaxSetup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonUpRmpMaxSetup, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonUpRmpMaxSetup, lv_color_hex(0xD1D5DB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonUpRmpMaxSetup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_buttonUpRmpMaxSetup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_buttonUpRmpMaxSetup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelUpRmpMaxSetup = lv_label_create(ui_buttonUpRmpMaxSetup);
    lv_obj_set_width(ui_labelUpRmpMaxSetup, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelUpRmpMaxSetup, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelUpRmpMaxSetup, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelUpRmpMaxSetup, "+");
    lv_obj_set_style_text_color(ui_labelUpRmpMaxSetup, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelUpRmpMaxSetup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelUpRmpMaxSetup, &ui_font_MonterLight36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonUpTimeMaxSetup = lv_button_create(ui_SetupRamp);
    lv_obj_set_width(ui_buttonUpTimeMaxSetup, 60);
    lv_obj_set_height(ui_buttonUpTimeMaxSetup, 40);
    lv_obj_set_x(ui_buttonUpTimeMaxSetup, 200);
    lv_obj_set_y(ui_buttonUpTimeMaxSetup, 76);
    lv_obj_set_align(ui_buttonUpTimeMaxSetup, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonUpTimeMaxSetup, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonUpTimeMaxSetup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonUpTimeMaxSetup, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonUpTimeMaxSetup, lv_color_hex(0xD1D5DB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonUpTimeMaxSetup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_buttonUpTimeMaxSetup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_buttonUpTimeMaxSetup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelUpTimeMaxSetup = lv_label_create(ui_buttonUpTimeMaxSetup);
    lv_obj_set_width(ui_labelUpTimeMaxSetup, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelUpTimeMaxSetup, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelUpTimeMaxSetup, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelUpTimeMaxSetup, "+");
    lv_obj_set_style_text_color(ui_labelUpTimeMaxSetup, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelUpTimeMaxSetup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelUpTimeMaxSetup, &ui_font_MonterLight36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonDownRmpMaxSetup = lv_button_create(ui_SetupRamp);
    lv_obj_set_width(ui_buttonDownRmpMaxSetup, 60);
    lv_obj_set_height(ui_buttonDownRmpMaxSetup, 40);
    lv_obj_set_x(ui_buttonDownRmpMaxSetup, 129);
    lv_obj_set_y(ui_buttonDownRmpMaxSetup, 18);
    lv_obj_set_align(ui_buttonDownRmpMaxSetup, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonDownRmpMaxSetup, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonDownRmpMaxSetup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonDownRmpMaxSetup, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonDownRmpMaxSetup, lv_color_hex(0xD1D5DB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonDownRmpMaxSetup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_buttonDownRmpMaxSetup, lv_color_hex(0x231F20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_buttonDownRmpMaxSetup, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_buttonDownRmpMaxSetup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_buttonDownRmpMaxSetup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelDownRmpMaxSetup = lv_label_create(ui_buttonDownRmpMaxSetup);
    lv_obj_set_width(ui_labelDownRmpMaxSetup, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelDownRmpMaxSetup, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelDownRmpMaxSetup, 0);
    lv_obj_set_y(ui_labelDownRmpMaxSetup, -3);
    lv_obj_set_align(ui_labelDownRmpMaxSetup, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelDownRmpMaxSetup, "-");
    lv_obj_set_style_text_color(ui_labelDownRmpMaxSetup, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelDownRmpMaxSetup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelDownRmpMaxSetup, &ui_font_MonterLight48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonDownTimeMaxSetup = lv_button_create(ui_SetupRamp);
    lv_obj_set_width(ui_buttonDownTimeMaxSetup, 60);
    lv_obj_set_height(ui_buttonDownTimeMaxSetup, 40);
    lv_obj_set_x(ui_buttonDownTimeMaxSetup, 129);
    lv_obj_set_y(ui_buttonDownTimeMaxSetup, 76);
    lv_obj_set_align(ui_buttonDownTimeMaxSetup, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonDownTimeMaxSetup, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonDownTimeMaxSetup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonDownTimeMaxSetup, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonDownTimeMaxSetup, lv_color_hex(0xD1D5DB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonDownTimeMaxSetup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_buttonDownTimeMaxSetup, lv_color_hex(0x231F20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_buttonDownTimeMaxSetup, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_buttonDownTimeMaxSetup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_buttonDownTimeMaxSetup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelDownTimeMaxSetup = lv_label_create(ui_buttonDownTimeMaxSetup);
    lv_obj_set_width(ui_labelDownTimeMaxSetup, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelDownTimeMaxSetup, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelDownTimeMaxSetup, 0);
    lv_obj_set_y(ui_labelDownTimeMaxSetup, -3);
    lv_obj_set_align(ui_labelDownTimeMaxSetup, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelDownTimeMaxSetup, "-");
    lv_obj_set_style_text_color(ui_labelDownTimeMaxSetup, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelDownTimeMaxSetup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelDownTimeMaxSetup, &ui_font_MonterLight48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonSaveSetupRamp = lv_button_create(ui_SetupRamp);
    lv_obj_set_width(ui_buttonSaveSetupRamp, 60);
    lv_obj_set_height(ui_buttonSaveSetupRamp, 40);
    lv_obj_set_x(ui_buttonSaveSetupRamp, 200);
    lv_obj_set_y(ui_buttonSaveSetupRamp, 128);
    lv_obj_set_align(ui_buttonSaveSetupRamp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonSaveSetupRamp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonSaveSetupRamp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonSaveSetupRamp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonSaveSetupRamp, lv_color_hex(0x10B981), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonSaveSetupRamp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_buttonSaveSetupRamp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_buttonSaveSetupRamp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelSaveSetupRamp = lv_label_create(ui_buttonSaveSetupRamp);
    lv_obj_set_width(ui_labelSaveSetupRamp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelSaveSetupRamp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelSaveSetupRamp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelSaveSetupRamp, "Save");
    lv_obj_set_style_text_color(ui_labelSaveSetupRamp, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelSaveSetupRamp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelSaveSetupRamp, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonResetSetupRamp = lv_button_create(ui_SetupRamp);
    lv_obj_set_width(ui_buttonResetSetupRamp, 60);
    lv_obj_set_height(ui_buttonResetSetupRamp, 40);
    lv_obj_set_x(ui_buttonResetSetupRamp, 129);
    lv_obj_set_y(ui_buttonResetSetupRamp, 128);
    lv_obj_set_align(ui_buttonResetSetupRamp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonResetSetupRamp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonResetSetupRamp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonResetSetupRamp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonResetSetupRamp, lv_color_hex(0xE64A4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonResetSetupRamp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_buttonResetSetupRamp, lv_color_hex(0x231F20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_buttonResetSetupRamp, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_buttonResetSetupRamp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_buttonResetSetupRamp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelResetSetupRamp = lv_label_create(ui_buttonResetSetupRamp);
    lv_obj_set_width(ui_labelResetSetupRamp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelResetSetupRamp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelResetSetupRamp, 0);
    lv_obj_set_y(ui_labelResetSetupRamp, 1);
    lv_obj_set_align(ui_labelResetSetupRamp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelResetSetupRamp, "Reset");
    lv_obj_set_style_text_color(ui_labelResetSetupRamp, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelResetSetupRamp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelResetSetupRamp, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelDataMinSpeed = lv_label_create(ui_SetupRamp);
    lv_obj_set_width(ui_labelDataMinSpeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelDataMinSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelDataMinSpeed, -27);
    lv_obj_set_y(ui_labelDataMinSpeed, -90);
    lv_obj_set_align(ui_labelDataMinSpeed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelDataMinSpeed, "0");
    lv_obj_set_style_text_color(ui_labelDataMinSpeed, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelDataMinSpeed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelDataMinSpeed, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelDataMinTime = lv_label_create(ui_SetupRamp);
    lv_obj_set_width(ui_labelDataMinTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelDataMinTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelDataMinTime, -27);
    lv_obj_set_y(ui_labelDataMinTime, -39);
    lv_obj_set_align(ui_labelDataMinTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelDataMinTime, "0");
    lv_obj_set_style_text_color(ui_labelDataMinTime, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelDataMinTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelDataMinTime, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelDataMaxSpeed = lv_label_create(ui_SetupRamp);
    lv_obj_set_width(ui_labelDataMaxSpeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelDataMaxSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelDataMaxSpeed, -27);
    lv_obj_set_y(ui_labelDataMaxSpeed, 14);
    lv_obj_set_align(ui_labelDataMaxSpeed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelDataMaxSpeed, "0");
    lv_obj_set_style_text_color(ui_labelDataMaxSpeed, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelDataMaxSpeed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelDataMaxSpeed, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelDataMaxTime = lv_label_create(ui_SetupRamp);
    lv_obj_set_width(ui_labelDataMaxTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelDataMaxTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelDataMaxTime, -27);
    lv_obj_set_y(ui_labelDataMaxTime, 72);
    lv_obj_set_align(ui_labelDataMaxTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelDataMaxTime, "0");
    lv_obj_set_style_text_color(ui_labelDataMaxTime, lv_color_hex(0x061014), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelDataMaxTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelDataMaxTime, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_buttonHomeSetupRamp, ui_event_buttonHomeSetupRamp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonSetupRampMode1, ui_event_buttonSetupRampMode1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonSetupRampMode2, ui_event_buttonSetupRampMode2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonSetupRampMode3, ui_event_buttonSetupRampMode3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonDownRmpMinSetup, ui_event_buttonDownRmpMinSetup, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonUpRmpMinSetup, ui_event_buttonUpRmpMinSetup, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonUpTimeMinSetup, ui_event_buttonUpTimeMinSetup, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonDownTimeMinSetup, ui_event_buttonDownTimeMinSetup, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonUpRmpMaxSetup, ui_event_buttonUpRmpMaxSetup, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonUpTimeMaxSetup, ui_event_buttonUpTimeMaxSetup, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonDownRmpMaxSetup, ui_event_buttonDownRmpMaxSetup, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonDownTimeMaxSetup, ui_event_buttonDownTimeMaxSetup, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonSaveSetupRamp, ui_event_buttonSaveSetupRamp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonResetSetupRamp, ui_event_buttonResetSetupRamp, LV_EVENT_ALL, NULL);

}

void ui_SetupRamp_screen_destroy(void)
{
    if(ui_SetupRamp) lv_obj_del(ui_SetupRamp);

    // NULL screen variables
    ui_SetupRamp = NULL;
    ui_bgrSetupRamp = NULL;
    ui_buttonHomeSetupRamp = NULL;
    ui_buttonSetupRampMode1 = NULL;
    ui_labelSetupRampMode1 = NULL;
    ui_buttonSetupRampMode2 = NULL;
    ui_labelSetupRampMode2 = NULL;
    ui_buttonSetupRampMode3 = NULL;
    ui_labelSetupRampMode3 = NULL;
    ui_buttonDownRmpMinSetup = NULL;
    ui_labelDownRmpMinSetup = NULL;
    ui_buttonUpRmpMinSetup = NULL;
    ui_labelUpRmpMinSetup = NULL;
    ui_buttonUpTimeMinSetup = NULL;
    ui_labelUpTimeMinSetup = NULL;
    ui_buttonDownTimeMinSetup = NULL;
    ui_labelDownTimeMinSetup = NULL;
    ui_buttonUpRmpMaxSetup = NULL;
    ui_labelUpRmpMaxSetup = NULL;
    ui_buttonUpTimeMaxSetup = NULL;
    ui_labelUpTimeMaxSetup = NULL;
    ui_buttonDownRmpMaxSetup = NULL;
    ui_labelDownRmpMaxSetup = NULL;
    ui_buttonDownTimeMaxSetup = NULL;
    ui_labelDownTimeMaxSetup = NULL;
    ui_buttonSaveSetupRamp = NULL;
    ui_labelSaveSetupRamp = NULL;
    ui_buttonResetSetupRamp = NULL;
    ui_labelResetSetupRamp = NULL;
    ui_labelDataMinSpeed = NULL;
    ui_labelDataMinTime = NULL;
    ui_labelDataMaxSpeed = NULL;
    ui_labelDataMaxTime = NULL;

}
