// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: ui_spin_coater

#ifndef UI_SETUPRAMP_H
#define UI_SETUPRAMP_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SetupRamp
extern void ui_SetupRamp_screen_init(void);
extern void ui_SetupRamp_screen_destroy(void);
extern lv_obj_t * ui_SetupRamp;
extern lv_obj_t * ui_bgrSetupRamp;
extern void ui_event_buttonHomeSetupRamp(lv_event_t * e);
extern lv_obj_t * ui_buttonHomeSetupRamp;
extern void ui_event_buttonSetupRampMode1(lv_event_t * e);
extern lv_obj_t * ui_buttonSetupRampMode1;
extern lv_obj_t * ui_labelSetupRampMode1;
extern void ui_event_buttonSetupRampMode2(lv_event_t * e);
extern lv_obj_t * ui_buttonSetupRampMode2;
extern lv_obj_t * ui_labelSetupRampMode2;
extern void ui_event_buttonSetupRampMode3(lv_event_t * e);
extern lv_obj_t * ui_buttonSetupRampMode3;
extern lv_obj_t * ui_labelSetupRampMode3;
extern void ui_event_buttonDownRmpMinSetup(lv_event_t * e);
extern lv_obj_t * ui_buttonDownRmpMinSetup;
extern lv_obj_t * ui_labelDownRmpMinSetup;
extern void ui_event_buttonUpRmpMinSetup(lv_event_t * e);
extern lv_obj_t * ui_buttonUpRmpMinSetup;
extern lv_obj_t * ui_labelUpRmpMinSetup;
extern void ui_event_buttonUpTimeMinSetup(lv_event_t * e);
extern lv_obj_t * ui_buttonUpTimeMinSetup;
extern lv_obj_t * ui_labelUpTimeMinSetup;
extern void ui_event_buttonDownTimeMinSetup(lv_event_t * e);
extern lv_obj_t * ui_buttonDownTimeMinSetup;
extern lv_obj_t * ui_labelDownTimeMinSetup;
extern void ui_event_buttonUpRmpMaxSetup(lv_event_t * e);
extern lv_obj_t * ui_buttonUpRmpMaxSetup;
extern lv_obj_t * ui_labelUpRmpMaxSetup;
extern void ui_event_buttonUpTimeMaxSetup(lv_event_t * e);
extern lv_obj_t * ui_buttonUpTimeMaxSetup;
extern lv_obj_t * ui_labelUpTimeMaxSetup;
extern void ui_event_buttonDownRmpMaxSetup(lv_event_t * e);
extern lv_obj_t * ui_buttonDownRmpMaxSetup;
extern lv_obj_t * ui_labelDownRmpMaxSetup;
extern void ui_event_buttonDownTimeMaxSetup(lv_event_t * e);
extern lv_obj_t * ui_buttonDownTimeMaxSetup;
extern lv_obj_t * ui_labelDownTimeMaxSetup;
extern void ui_event_buttonSaveSetupRamp(lv_event_t * e);
extern lv_obj_t * ui_buttonSaveSetupRamp;
extern lv_obj_t * ui_labelSaveSetupRamp;
extern void ui_event_buttonResetSetupRamp(lv_event_t * e);
extern lv_obj_t * ui_buttonResetSetupRamp;
extern lv_obj_t * ui_labelResetSetupRamp;
extern lv_obj_t * ui_labelDataMinSpeed;
extern lv_obj_t * ui_labelDataMinTime;
extern lv_obj_t * ui_labelDataMaxSpeed;
extern lv_obj_t * ui_labelDataMaxTime;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

