// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: ui_spin_coater

#ifndef _UI_SPIN_COATER_UI_H
#define _UI_SPIN_COATER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Home.h"
#include "screens/ui_Analog.h"
#include "screens/ui_Digital.h"
#include "screens/ui_Setup.h"
#include "screens/ui_SetupRamp.h"
#include "screens/ui_Ramp.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_spin_coater_png);    // assets/SPIN COATER.png
LV_IMG_DECLARE(ui_img_analogscreen_png);    // assets/AnalogScreen.png
LV_IMG_DECLARE(ui_img_670667251);    // assets/Screenshot 2025-10-11 152237.png
LV_IMG_DECLARE(ui_img_digitalscreen_png);    // assets/DigitalScreen.png
LV_IMG_DECLARE(ui_img_setupscreen_png);    // assets/SetupScreen.png
LV_IMG_DECLARE(ui_img_home_png);    // assets/home.png
LV_IMG_DECLARE(ui_img_setuprampscreen_png);    // assets/SetupRampScreen.png
LV_IMG_DECLARE(ui_img_rampscreen_png);    // assets/RampScreen.png

// FONTS
LV_FONT_DECLARE(ui_font_MonterLight48);
LV_FONT_DECLARE(ui_font_MonterLight30);
LV_FONT_DECLARE(ui_font_MonterLight36);
LV_FONT_DECLARE(ui_font_MonterLight32);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
