// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: ui_spin_coater

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Button_Select_Mode_Analog(lv_event_t * e);
void Button_Select_Mode_Digital(lv_event_t * e);
void Button_Select_Mode_Ramp(lv_event_t * e);
void Button_Select_Mode_Setup(lv_event_t * e);
void Button_SetSateIDLE_Analog(lv_event_t * e);
void Button_StopAnalog(lv_event_t * e);
void Button_StartAnalog(lv_event_t * e);
void Button_SetRpm(lv_event_t * e);
void Button_StopDigital(lv_event_t * e);
void Button_StartDigital(lv_event_t * e);
void Button_UpInc(lv_event_t * e);
void Button_DownInc(lv_event_t * e);
void ButtonUpSrpm(lv_event_t * e);
void Button_DownSrpm(lv_event_t * e);
void Button_SetStateIDLE_Digital(lv_event_t * e);
void Button_Select_Mode1_Setup(lv_event_t * e);
void Button_Select_Mode2_Setup(lv_event_t * e);
void Button_Select_Mode3_Setup(lv_event_t * e);
void Button_Down_Min_Speed(lv_event_t * e);
void Button_Up_Min_Speed(lv_event_t * e);
void Button_Up_Min_Time(lv_event_t * e);
void Button_Down_Min_Time(lv_event_t * e);
void Button_Up_Max_Speed(lv_event_t * e);
void Button_Up_Max_Time(lv_event_t * e);
void Button_Down_Max_Speed(lv_event_t * e);
void Button_Down_Max_Time(lv_event_t * e);
void Button_Save_Setup_Ramp(lv_event_t * e);
void Button_Reset_Setup_Ramp(lv_event_t * e);
void Button_StopRamp(lv_event_t * e);
void Button_StartRamp(lv_event_t * e);
void Button_SetStateIDLE_Ramp(lv_event_t * e);
void Button_Select_Mode1_Ramp(lv_event_t * e);
void Button_Select_Mode2_Ramp(lv_event_t * e);
void Button_Select_Mode3_Ramp(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
