// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: ui_spin_coater

#include "ui.h"
#include "app_control.h"
#include "screen_analog.h"
#include "screen_digital.h"
#include "screen_ramp.h"

void Button_Select_Mode_Analog(lv_event_t * e)
{
	App_Control_SelectMode(APP_MODE_ANALOG);
}

void Button_Select_Mode_Digital(lv_event_t * e)
{
	App_Control_SelectMode(APP_MODE_DIGITAL);
}

void Button_Select_Mode_Ramp(lv_event_t * e)
{
	App_Control_SelectMode(APP_MODE_RAMP);
}

void Button_Select_Mode_Setup(lv_event_t * e)
{
	App_Control_SelectMode(APP_MODE_SETTING);
}

void Button_SetSateIDLE_Analog(lv_event_t * e)
{
	App_Analog_Set_IDLE();
}

void Button_StopAnalog(lv_event_t * e)
{
	App_Analog_Stop();
}

void Button_StartAnalog(lv_event_t * e)
{
	App_Analog_Start();
}

void Button_SetRpm(lv_event_t * e)
{
	App_Analog_SetRpm();
}

void Button_StopDigital(lv_event_t * e)
{
	App_Digital_Stop();
}

void Button_StartDigital(lv_event_t * e)
{
	App_Digital_Start();
}

void Button_UpInc(lv_event_t * e)
{
	App_Digital_Incre_Inc();
}

void Button_DownInc(lv_event_t * e)
{
	App_Digital_Decre_Inc();
}

void ButtonUpSrpm(lv_event_t * e)
{
	App_Digital_Incre_SRPM();
}

void Button_DownSrpm(lv_event_t * e)
{
	App_Digital_Decre_SRPM();
}

void Button_SetStateIDLE_Digital(lv_event_t * e)
{
	App_Digital_Set_IDLE();
}

void Button_Select_Mode1_Setup(lv_event_t * e)
{
	App_Ramp_SelectSetupMode(1);
}

void Button_Select_Mode2_Setup(lv_event_t * e)
{
	App_Ramp_SelectSetupMode(2);
}

void Button_Select_Mode3_Setup(lv_event_t * e)
{
	App_Ramp_SelectSetupMode(3);
}

void Button_Down_Min_Speed(lv_event_t * e)
{
	App_Ramp_Decrese_MIN_Speed();
}

void Button_Up_Min_Speed(lv_event_t * e)
{
	App_Ramp_Increase_MIN_Speed();
}

void Button_Up_Min_Time(lv_event_t * e)
{
	App_Ramp_Increase_MIN_Time();
}

void Button_Down_Min_Time(lv_event_t * e)
{
	App_Ramp_Decrese_MIN_Time();
}

void Button_Up_Max_Speed(lv_event_t * e)
{
	App_Ramp_Increase_MAX_Speed();
}

void Button_Up_Max_Time(lv_event_t * e)
{
	App_Ramp_Increase_MAX_Time();
}

void Button_Down_Max_Speed(lv_event_t * e)
{
	App_Ramp_Decrese_MAX_Speed();
}

void Button_Down_Max_Time(lv_event_t * e)
{
	App_Ramp_Decrese_MAX_Time();
}

void Button_Save_Setup_Ramp(lv_event_t * e)
{
	App_Ramp_Save();
}

void Button_Reset_Setup_Ramp(lv_event_t * e)
{
	App_Ramp_ResetSetup();
}

void Button_StopRamp(lv_event_t * e)
{
	App_Ramp_Stop();
}

void Button_StartRamp(lv_event_t * e)
{
	App_Ramp_Start();
}

void Button_SetStateIDLE_Ramp(lv_event_t * e)
{
	App_Ramp_Set_IDLE();
}

void Button_Select_Mode1_Ramp(lv_event_t * e)
{
	App_Ramp_SelectMode(1);
}

void Button_Select_Mode2_Ramp(lv_event_t * e)
{
	App_Ramp_SelectMode(2);
}

void Button_Select_Mode3_Ramp(lv_event_t * e)
{
	App_Ramp_SelectMode(3);
}
